```{r global-knitr-options, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE)
```




```{r}
# Quadratzahlen von 1 bis 10 berechnen:
zahlen <- (1:10)^2

# Eine davon auswählen, wiederum zufällig:
gezogene_zahl <- sample(zahlen, 1)


# Antwort berechnen:
richtige_antwort <- sqrt(gezogene_zahl)

# Falsche Antworten zufällig bestimmen:
falsche_antworten <- 
  zahlen[-richtige_antwort] %>% 
  sample(4) %>% 
  sqrt()
```


```{r}
# Antwortoptionen erstellen:

# entweder so:
items <-
  num_to_schoice(
    correct = richtige_antwort,
    digits = 0,
    range = c(0, 200)
  )


# oder so:
items <-
  tibble(
    questions = c(richtige_antwort, falsche_antworten),
    solutions = c(TRUE, FALSE, FALSE, FALSE, FALSE)
  ) %>% 
  sample_n( size = nrow(.))  # Reihenfolge der Antworten mischen
```




Question
========

Was ist das Ergebnis dieser Rechnung:

$\sqrt{`r gezogene_zahl`}$

```{r questionlist, results = "asis", echo = FALSE}
# Liste mit Antwortoptionen erzeugen:
answerlist(items$questions, markup = "markdown")
```


Solution
========

Die Wurzel von `r gezogene_zahl` ist `r `richtige_antwort`.



```{r solutionlist,  results = "asis", echo = FALSE}
# Liste mit Richtig/Falsch pro Antwortoption erzeugen:
answerlist(ifelse(items$solutions, "Richtig", "Falsch"), markup = "markdown")
```






Meta-information
================
extype: schoice 
exsolution: `r mchoice2string(items$solutions)`
exname: numerisch3
expoints: 1
exdyn: TRUE



